name: Build APK - Final Fix

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Apply Gradle fixes and prepare Android build
      run: |
        cd ios_camera_flutter_app
        
        echo "=== Applying Final Gradle Fixes ==="
        
        # Ensure Android gradle configuration is fully compatible
        mkdir -p android/gradle/wrapper
        
        # Update Gradle wrapper to compatible version
        cat > android/gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
        EOF
        
        # Create comprehensive root build.gradle
        cat > android/build.gradle << 'EOF'
        buildscript {
            ext.kotlin_version = '1.7.10'
            repositories {
                google()
                mavenCentral()
            }

            dependencies {
                classpath 'com.android.tools.build:gradle:7.3.0'
                classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            }
        }

        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }

        rootProject.buildDir = '../build'
        subprojects {
            project.buildDir = "${rootProject.buildDir}/${project.name}"
        }
        subprojects {
            project.evaluationDependsOn(':app')
        }

        task clean(type: Delete) {
            delete rootProject.buildDir
        }
        EOF
        
        # Update app/build.gradle for optimal compatibility
        cat > android/app/build.gradle << 'EOF'
        def localProperties = new Properties()
        def localPropertiesFile = rootProject.file('local.properties')
        if (localPropertiesFile.exists()) {
            localPropertiesFile.withReader('UTF-8') { reader ->
                localProperties.load(reader)
            }
        }

        def flutterRoot = localProperties.getProperty('flutter.sdk')
        if (flutterRoot == null) {
            throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
        }

        def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
        if (flutterVersionCode == null) {
            flutterVersionCode = '1'
        }

        def flutterVersionName = localProperties.getProperty('flutter.versionName')
        if (flutterVersionName == null) {
            flutterVersionName = '1.0'
        }

        apply plugin: 'com.android.application'
        apply plugin: 'kotlin-android'
        apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

        android {
            compileSdkVersion flutter.compileSdkVersion
            ndkVersion flutter.ndkVersion

            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }

            kotlinOptions {
                jvmTarget = '1.8'
            }

            sourceSets {
                main.java.srcDirs += 'src/main/kotlin'
            }

            defaultConfig {
                applicationId "com.example.ios_camera_flutter_app"
                minSdkVersion flutter.minSdkVersion
                targetSdkVersion flutter.targetSdkVersion
                versionCode flutterVersionCode.toInteger()
                versionName flutterVersionName
            }

            buildTypes {
                release {
                    signingConfig signingConfigs.debug
                }
            }
        }

        flutter {
            source '../..'
        }

        dependencies {
            implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        }
        EOF
        
        # Fix MainActivity package and embedding
        mkdir -p android/app/src/main/kotlin/com/example/ios_camera_flutter_app
        cat > android/app/src/main/kotlin/com/example/ios_camera_flutter_app/MainActivity.kt << 'EOF'
        package com.example.ios_camera_flutter_app

        import io.flutter.embedding.android.FlutterActivity

        class MainActivity : FlutterActivity()
        EOF
        
        # Update AndroidManifest with camera permissions
        cat > android/app/src/main/AndroidManifest.xml << 'EOF'
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <!-- Camera permissions -->
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-permission android:name="android.permission.RECORD_AUDIO" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
            
            <uses-feature android:name="android.hardware.camera" android:required="true" />
            <uses-feature android:name="android.hardware.camera.autofocus" />
            
            <application
                android:label="iOS Camera App"
                android:name="${applicationName}"
                android:icon="@mipmap/ic_launcher">
                <activity
                    android:name="com.example.ios_camera_flutter_app.MainActivity"
                    android:exported="true"
                    android:launchMode="singleTop"
                    android:taskAffinity=""
                    android:theme="@style/LaunchTheme"
                    android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                    android:hardwareAccelerated="true"
                    android:windowSoftInputMode="adjustResize">
                    <meta-data
                      android:name="io.flutter.embedding.android.NormalTheme"
                      android:resource="@style/NormalTheme"
                      />
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                </activity>
                <meta-data
                    android:name="flutterEmbedding"
                    android:value="2" />
            </application>
            <queries>
                <intent>
                    <action android:name="android.intent.action.PROCESS_TEXT"/>
                    <data android:mimeType="text/plain"/>
                </intent>
            </queries>
        </manifest>
        EOF
        
        # Make gradle wrapper executable
        chmod +x android/gradlew
        
        echo "=== Configuration Verification ==="
        echo "--- Gradle Wrapper ---"
        cat android/gradle/wrapper/gradle-wrapper.properties
        echo "--- Root build.gradle ---"
        head -15 android/build.gradle
        echo "--- App build.gradle ---"
        head -15 android/app/build.gradle
        echo "--- MainActivity ---"
        cat android/app/src/main/kotlin/com/example/ios_camera_flutter_app/MainActivity.kt
        
    - name: Flutter Clean and Dependencies
      run: |
        cd ios_camera_flutter_app
        flutter clean
        flutter pub get
        
    - name: Build APK with Fixed Configuration
      run: |
        cd ios_camera_flutter_app
        echo "=== Starting APK Build with Final Fixes ==="
        flutter build apk --release --verbose
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: camera-app-final-release
        path: ios_camera_flutter_app/build/app/outputs/flutter-apk/app-release.apk
        
    - name: Build Results Summary
      if: always()
      run: |
        cd ios_camera_flutter_app
        echo "=== Build Summary ==="
        if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
          echo "✅ APK Build Successful!"
          ls -la build/app/outputs/flutter-apk/app-release.apk
          echo "APK Size: $(du -h build/app/outputs/flutter-apk/app-release.apk | cut -f1)"
        else
          echo "❌ APK Build Failed"
          find build -name "*.apk" 2>/dev/null || echo "No APK files found"
        fi